export const PARCEL_SALE_ABI = [
  {
    type: 'constructor',
    inputs: [
      { name: '_core', type: 'address' },
      { name: '_landToken', type: 'address' },
      { name: '_router', type: 'address' },
      { name: '_weth', type: 'address' },
      { name: 'initialOwner', type: 'address' },
      { name: '_startPrice', type: 'uint256' },
      { name: '_priceIncrement', type: 'uint256' },
      { name: '_maxPrice', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getCurrentPrice',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getParcel',
    inputs: [{ name: 'parcelNumber', type: 'uint256' }],
    outputs: [
      { name: 'x', type: 'uint256' },
      { name: 'y', type: 'uint256' },
      { name: 'size', type: 'uint256' },
      { name: 'currentPrice', type: 'uint256' },
      { name: 'sold', type: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getStats',
    inputs: [],
    outputs: [
      { name: '_totalParcels', type: 'uint256' },
      { name: '_soldCount', type: 'uint256' },
      { name: '_availableCount', type: 'uint256' },
      { name: '_totalETHCollected', type: 'uint256' },
      { name: '_totalLiquidityCreated', type: 'uint256' },
      { name: '_totalLPBurned', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isAvailable',
    inputs: [{ name: 'parcelNumber', type: 'uint256' }],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'purchaseParcel',
    inputs: [{ name: 'parcelNumber', type: 'uint256' }],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'startPrice',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'priceIncrement',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'maxPrice',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'soldCount',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'ParcelPurchased',
    inputs: [
      { name: 'parcelNumber', type: 'uint256', indexed: true },
      { name: 'buyer', type: 'address', indexed: true },
      { name: 'priceETH', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'LiquidityAdded',
    inputs: [
      { name: 'ethAmount', type: 'uint256', indexed: false },
      { name: 'landAmount', type: 'uint256', indexed: false },
      { name: 'lpTokens', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'LPBurned',
    inputs: [{ name: 'lpTokens', type: 'uint256', indexed: false }],
  },
] as const;
